apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-minikube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-minikube-app
  template:
    metadata:
      labels:
        app: php-minikube-app
    spec:
      containers:
      - name: php-minikube-app
        image: pradeeprai87/php-minikube-app:latest
        ports:
        - containerPort: 80
        envFrom:
        # - configMapRef:
          #name: php-config
        - secretRef:
            name: php-app-secrets
