apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: php-app-external-secret
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: php-app-secrets
  refreshInterval: 1m
  data:
    - secretKey: WELCOME_MESSAGE
      remoteRef:
        key: php-app-secret
        property: WELCOME_MESSAGE
